name: ec2-deploy

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - aws
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install    
#      - name: Test
#        run: npm test
        env:
          CI: true
      - name: Generate build
        run: npm run build
      - name: Log dir
        run: |
          ls -la
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: react-github-actions-build
          path: dist
